name: ci
on:
  push:
    branches:
      - master
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ~1.19

      - name: Check out code
        uses: actions/checkout@v3

      - name: Linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.48.0

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.19

      - name: Check out code
        uses: actions/checkout@v3

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: make build

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ~1.19

      - name: Check out code
        uses: actions/checkout@v3

      - name: Tests
        run: make test
